try {
  print(non_existent_variable)
  print("hmm...")
} catch err {
  print("caught exception: " + err)
}

throw "custom exception"
